name: flutterboard_example
description: Example app for the flutterboard package.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutterboard:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
